language: python
python:
  - 2.7
install:
  - travis_retry pip install pylint
  - travis_retry pip install -r requirements.txt
script:
  - pylint --rcfile=.pylintrc Gateway/*.py Gateway/lib/*.py Gateway/lib/routers/*.py
  - pylint --rcfile=.pylintrc Server/*.py Server/lib/*.py
