#!/bin/sh
### BEGIN INIT INFO
# Provides:          Inora server instance
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       starts or stops instance of Inora server
### END INIT INFO

CONFIG=/etc/default/inora

# don't accept config vars from the shell environment
unset INORA_HOME RUNAS PIDFILE PYTHON_BIN LOGFILE

# try loading the configuration file
[ -r "$CONFIG" ] && . "$CONFIG" \
        || echo "${CONFIG} unreadable, falling back to default settings" >&2

## Edit user configuation in /etc/config/inora to change
## the defaults
username=${RUNAS-root}
homedir=${INORA_HOME-/opt/inora}
pidfile=${PIDFILE-/var/run/inora.pid}
PYTHONBIN=${PYTHON_BIN-/usr/bin/python}
logfile=`grep args ${homedir}/inora.conf |  sed "s/.*'\([^']*\)'.*/\1/"`
##

SCRIPT=$homedir/inora_server.py


# basic checks
([ -x "$PYTHONBIN" ] && [ -f "${homedir}/inora_server.py" ]) || {
        echo "init script setup failed basic sanity checks, aborting!" >&2
        exit 1;
}

start() {
  if [ -f ${pidfile} ] && kill -0 $(cat ${pidfile}) > /dev/null 2>&1; then
    echo 'Service already running' >&2
    exit 1
  fi
  echo 'Starting service…'
  local CMD="${PYTHONBIN} ${SCRIPT} > \"$logfile\" &  echo \$!"
  su -c "$CMD" $username >  "$pidfile"
  echo 'Service started'
}

stop() {
  if [ ! -f "${pidfile}" ] || ! kill -0 $(cat "${pidfile}"); then
    echo 'Service not running' >&2
    exit 1
  fi
  echo 'Stopping service…'
  kill -15 $(cat "${pidfile}") && rm -f "${pidfile}"
  echo 'Service stopped'
}
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac
